/* This file has been auto-generated by bin/generateSvgIcons.js script */

import React from 'react'

export default (props) => {
  const svg = <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10 20h4V4h-4v16zm-6 0h4v-8H4v8zM16 9v11h4V9h-4z"/></svg>
  return React.cloneElement(svg, props)
}
