/* This file has been auto-generated by bin/generateSvgIcons.js script */

import React from 'react'

export default (props) => {
  const svg = <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><circle cx="12" cy="19" r="2"/><path d="M10 3h4v12h-4z"/></svg>
  return React.cloneElement(svg, props)
}
