/* This file has been auto-generated by bin/generateSvgIcons.js script */

import React from 'react'

export default (props) => {
  const svg = <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg>
  return React.cloneElement(svg, props)
}
