/* This file has been auto-generated by bin/generateSvgIcons.js script */

import React from 'react'

export default (props) => {
  const svg = <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M5 4v3h5.5v12h3V7H19V4z"/></svg>
  return React.cloneElement(svg, props)
}
